ALTER TABLE "Review"
  ADD COLUMN IF NOT EXISTS "cleanliness" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "comfort" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "location" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "facilities" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "staff" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "valueForMoney" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "hostReply" TEXT,
  ADD COLUMN IF NOT EXISTS "hostRepliedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS "ReviewImage" (
  "id"        TEXT NOT NULL,
  "reviewId"  TEXT NOT NULL,
  "url"       TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ReviewImage_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ReviewImage_reviewId_idx" ON "ReviewImage"("reviewId");

ALTER TABLE "ReviewImage"
  DROP CONSTRAINT IF EXISTS "ReviewImage_reviewId_fkey";

ALTER TABLE "ReviewImage"
  ADD CONSTRAINT "ReviewImage_reviewId_fkey"
  FOREIGN KEY ("reviewId") REFERENCES "Review"("id") ON DELETE CASCADE ON UPDATE CASCADE;
