export const CURRENT_VIETNAM_PROVINCES = [
  { name: "Hà Nội", code: "HN", type: "THANH_PHO" },
  { name: "Hải Phòng", code: "HP", type: "THANH_PHO" },
  { name: "Huế", code: "HUE", type: "THANH_PHO" },
  { name: "Đà Nẵng", code: "DNA", type: "THANH_PHO" },
  { name: "Cần Thơ", code: "CT", type: "THANH_PHO" },
  { name: "Thành phố Hồ Chí Minh", code: "HCM", type: "THANH_PHO" },
  { name: "An Giang", code: "AG", type: "TINH" },
  { name: "Bắc Ninh", code: "BN", type: "TINH" },
  { name: "Cà Mau", code: "CM", type: "TINH" },
  { name: "Cao Bằng", code: "CB", type: "TINH" },
  { name: "Đắk Lắk", code: "DL", type: "TINH" },
  { name: "Điện Biên", code: "DB", type: "TINH" },
  { name: "Đồng Nai", code: "DN", type: "TINH" },
  { name: "Đồng Tháp", code: "DT", type: "TINH" },
  { name: "Gia Lai", code: "GL", type: "TINH" },
  { name: "Hà Tĩnh", code: "HT", type: "TINH" },
  { name: "Hưng Yên", code: "HY", type: "TINH" },
  { name: "Khánh Hòa", code: "KH", type: "TINH" },
  { name: "Lai Châu", code: "LAI", type: "TINH" },
  { name: "Lâm Đồng", code: "LD", type: "TINH" },
  { name: "Lạng Sơn", code: "LS", type: "TINH" },
  { name: "Lào Cai", code: "LC", type: "TINH" },
  { name: "Nghệ An", code: "NA", type: "TINH" },
  { name: "Ninh Bình", code: "NB", type: "TINH" },
  { name: "Phú Thọ", code: "PT", type: "TINH" },
  { name: "Quảng Ngãi", code: "QNG", type: "TINH" },
  { name: "Quảng Ninh", code: "QN", type: "TINH" },
  { name: "Quảng Trị", code: "QT", type: "TINH" },
  { name: "Sơn La", code: "SL", type: "TINH" },
  { name: "Tây Ninh", code: "TN", type: "TINH" },
  { name: "Thái Nguyên", code: "TNG", type: "TINH" },
  { name: "Thanh Hóa", code: "TH", type: "TINH" },
  { name: "Tuyên Quang", code: "TQ", type: "TINH" },
  { name: "Vĩnh Long", code: "VL", type: "TINH" },
] as const;

export type CurrentVietnamProvince = (typeof CURRENT_VIETNAM_PROVINCES)[number];
